### ISSUE TITLE
Move this under reasonml-community?

### ISSUE THREAD

**Issue by chenglou** [poeschko/bs-glamor#4]
Hey @poeschko! Would you like to have bs-glamor live under the reasonml-community org? I think it could be a authoritative place for people to contribute to the glamor binding =).

(You'll preserve your access rights ofc.)

**Comment by emmenko** [comment]
@poeschko Any news on this? It's been inactive for some time, although I'm using it and find it **stable** so far 🚀

Anything we can do to help?

**Comment by poeschko** [comment]
Sorry! I dropped the ball on this... If you're still interested: YES, we can move this to reasonml-community.

I did just upgrade everything to the "new" Reason 3 syntax.

There's also https://github.com/SentiaAnalytics/bs-css now, not sure how it relates to this one.

**Comment by poeschko** [comment]
Done. This is now under https://github.com/reasonml-community/bs-glamor

**Comment by emmenko** [comment]
Btw: do we still need this repo? There is a new one from Glenn that has much better type support.

https://github.com/glennsl/bs-typed-glamor

I guess we can deprecate this...

**Comment by poeschko** [comment]
Fine by me.

**Comment by emmenko** [comment]
Just a suggestion 😇

/cc @glennsl WDYT? 👆

**Comment by glennsl** [comment]
I have no strong opinions :) There could still be a use for "untyped" glamor bindings, if you want to go superlight for example. Just as long as someone's willing to maintain it (every repository in this org should have a maintainer btw, see https://github.com/reasonml-community/meta)
